///////////////////////////////////////////////////////////////////
//
// Project RENOIR
// Release Notes Instant Reporter
//
// Reference application presented in
// Clean Architecture with .NET (MS Press) 2024
// Author: Dino Esposito
// 
//

using System.ComponentModel.DataAnnotations;

namespace Youbiquitous.Renoir.DomainModel.Documents;

/// <summary>
/// RELEASE-NOTE entity (properties)
/// </summary>
public partial class ReleaseNote : BaseEntity
{
    /// <summary>
    /// Ctor, mostly needed for EF and to save us an entire layer of DTOs
    /// </summary>
    public ReleaseNote()
    {
        Items = new List<ReleaseNoteItem>();
    }
    public ReleaseNote(long productId, string version)  
    {
        ProductId = productId;
        Version = version;
        Items = new List<ReleaseNoteItem>();
    }

    /// <summary>
    /// Unique ID (autogenerated)
    /// </summary>
    public long RefId { get; set; }

    /// <summary>
    /// Product ID
    /// </summary>
    public long ProductId { get; set; }

    /// <summary>
    /// Product the document refers to
    /// </summary>
    public Product RelatedProduct { get; set; }

    /// <summary>
    /// Version number
    /// </summary>
    [MaxLength(30)]
    public string Version { get; set; }

    /// <summary>
    /// Display release date
    /// </summary>
    public DateTime ReleaseDate { get; set; }

    /// <summary>
    /// Items in the document 
    /// </summary>
    public IEnumerable<ReleaseNoteItem> Items { get; set; }
}
