///////////////////////////////////////////////////////////////////
//
// Project RENOIR
// Release Notes Instant Reporter
//
// Reference application presented in
// Clean Architecture with .NET (MS Press) 2024
// Author: Dino Esposito
// 
//

using System.ComponentModel.DataAnnotations;

namespace Youbiquitous.Renoir.DomainModel.Documents;

/// <summary>
/// RELEASE-NOTE item entity (properties)
/// </summary>
public partial class ReleaseNoteItem : BaseEntity
{
    /// <summary>
    /// Ctor, mostly needed for EF and to save us an entire layer of DTOs
    /// </summary>
    public ReleaseNoteItem()
    {
    }

    /// <summary>
    /// Unique ID (autogenerated)
    /// </summary>
    public long RefId { get; set; }

    /// <summary>
    /// Reference to the parent ReleaseNote document (ID)
    /// </summary>
    public long DocumentId { get; set; }

    /// <summary>
    /// Reference to parent object
    /// </summary>
    public ReleaseNote RelatedDocument { get; set; }

    /// <summary>
    /// (Redundant) Reference to the product
    /// </summary>
    public long ProductId { get; set; }

    /// <summary>
    /// Type of line in the release note
    /// </summary>
    public ItemCategory Category { get; set; }

    /// <summary>
    /// Notes
    /// </summary>
    [MaxLength(140)]
    public string Description { get; set; }

    /// <summary>
    /// Free text
    /// </summary>
    [MaxLength(30)]
    public string Eta { get; set; }
}
