//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youbiquitous.Renoir.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youbiquitous.Renoir.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given email address already exists in the system.
        /// </summary>
        public static string Err_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("Err_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string Err_Generic {
            get {
                return ResourceManager.GetString("Err_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate both email and password.
        /// </summary>
        public static string Err_IncompleteCredentials {
            get {
                return ResourceManager.GetString("Err_IncompleteCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string Err_InvalidCredentials {
            get {
                return ResourceManager.GetString("Err_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string Err_InvalidEmail {
            get {
                return ResourceManager.GetString("Err_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to finalize credentials validation.
        /// </summary>
        public static string Err_InvalidHttpContext {
            get {
                return ResourceManager.GetString("Err_InvalidHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string Err_InvalidInput {
            get {
                return ResourceManager.GetString("Err_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number exceeded.
        /// </summary>
        public static string Err_MaxExceeded {
            get {
                return ResourceManager.GetString("Err_MaxExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIssing user name.
        /// </summary>
        public static string Err_MissingName {
            get {
                return ResourceManager.GetString("Err_MissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing password.
        /// </summary>
        public static string Err_MissingPassword {
            get {
                return ResourceManager.GetString("Err_MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing user role.
        /// </summary>
        public static string Err_MissingRole {
            get {
                return ResourceManager.GetString("Err_MissingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not complete the operation.
        /// </summary>
        public static string Err_OperationFailed {
            get {
                return ResourceManager.GetString("Err_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown just for test purposes.
        /// </summary>
        public static string Err_TestException {
            get {
                return ResourceManager.GetString("Err_TestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not authorized.
        /// </summary>
        public static string Err_UnauthorizedOperation {
            get {
                return ResourceManager.GetString("Err_UnauthorizedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weird, but no user seems to match provided identity.
        /// </summary>
        public static string Err_UserNotFound {
            get {
                return ResourceManager.GetString("Err_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully done!.
        /// </summary>
        public static string Msg_Done {
            get {
                return ResourceManager.GetString("Msg_Done", resourceCulture);
            }
        }
    }
}
