//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youbiquitous.Renoir.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youbiquitous.Renoir.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Label_Created {
            get {
                return ResourceManager.GetString("Label_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System dashboard.
        /// </summary>
        public static string Label_Dashboard {
            get {
                return ResourceManager.GetString("Label_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string Label_Deleting {
            get {
                return ResourceManager.GetString("Label_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string Label_DisplayName {
            get {
                return ResourceManager.GetString("Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Release Note.
        /// </summary>
        public static string Label_EditReleaseNote {
            get {
                return ResourceManager.GetString("Label_EditReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Roadmap.
        /// </summary>
        public static string Label_EditRoadmap {
            get {
                return ResourceManager.GetString("Label_EditRoadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the community.
        /// </summary>
        public static string Label_JoinCommunity {
            get {
                return ResourceManager.GetString("Label_JoinCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Label_Modified {
            get {
                return ResourceManager.GetString("Label_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Products.
        /// </summary>
        public static string Label_MyProducts {
            get {
                return ResourceManager.GetString("Label_MyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New binding.
        /// </summary>
        public static string Label_NewBinding {
            get {
                return ResourceManager.GetString("Label_NewBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password (Repeat).
        /// </summary>
        public static string Label_NewPasswordRepeat {
            get {
                return ResourceManager.GetString("Label_NewPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Release Note.
        /// </summary>
        public static string Label_NewReleaseNote {
            get {
                return ResourceManager.GetString("Label_NewReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Roadmap.
        /// </summary>
        public static string Label_NewRoadmap {
            get {
                return ResourceManager.GetString("Label_NewRoadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string Label_NewUser {
            get {
                return ResourceManager.GetString("Label_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role assigned.
        /// </summary>
        public static string Label_NoRole {
            get {
                return ResourceManager.GetString("Label_NoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Label_Notes {
            get {
                return ResourceManager.GetString("Label_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user selected.
        /// </summary>
        public static string Label_NoUser {
            get {
                return ResourceManager.GetString("Label_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Label_OldPassword {
            get {
                return ResourceManager.GetString("Label_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner(s).
        /// </summary>
        public static string Label_Owners {
            get {
                return ResourceManager.GetString("Label_Owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Label_Products {
            get {
                return ResourceManager.GetString("Label_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total products available for technical documentation.
        /// </summary>
        public static string Label_Products_Desc {
            get {
                return ResourceManager.GetString("Label_Products_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string Label_ReleaseNotes {
            get {
                return ResourceManager.GetString("Label_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of release note documents in the system.
        /// </summary>
        public static string Label_ReleaseNotes_Desc {
            get {
                return ResourceManager.GetString("Label_ReleaseNotes_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadmaps.
        /// </summary>
        public static string Label_Roadmaps {
            get {
                return ResourceManager.GetString("Label_Roadmaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of roadmap documents in the system.
        /// </summary>
        public static string Label_Roadmaps_Desc {
            get {
                return ResourceManager.GetString("Label_Roadmaps_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Label_Role {
            get {
                return ResourceManager.GetString("Label_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Page.
        /// </summary>
        public static string Label_SamplePage {
            get {
                return ResourceManager.GetString("Label_SamplePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since.
        /// </summary>
        public static string Label_Since {
            get {
                return ResourceManager.GetString("Label_Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay connected.
        /// </summary>
        public static string Label_StayConnected {
            get {
                return ResourceManager.GetString("Label_StayConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit [{0}].
        /// </summary>
        public static string Label_TitleEditUser {
            get {
                return ResourceManager.GetString("Label_TitleEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new product.
        /// </summary>
        public static string Label_TitleNewProduct {
            get {
                return ResourceManager.GetString("Label_TitleNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new user.
        /// </summary>
        public static string Label_TitleNewUser {
            get {
                return ResourceManager.GetString("Label_TitleNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered users.
        /// </summary>
        public static string Label_Users {
            get {
                return ResourceManager.GetString("Label_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total users allowed to use the platform.
        /// </summary>
        public static string Label_Users_Desc {
            get {
                return ResourceManager.GetString("Label_Users_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public name.
        /// </summary>
        public static string Placeholder_DisplayName {
            get {
                return ResourceManager.GetString("Placeholder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA.
        /// </summary>
        public static string Placeholder_Eta {
            get {
                return ResourceManager.GetString("Placeholder_Eta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the item....
        /// </summary>
        public static string Placeholder_ItemDescription {
            get {
                return ResourceManager.GetString("Placeholder_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password you want to use now.
        /// </summary>
        public static string Placeholder_NewPassword {
            get {
                return ResourceManager.GetString("Placeholder_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes....
        /// </summary>
        public static string Placeholder_Notes {
            get {
                return ResourceManager.GetString("Placeholder_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password currently in use.
        /// </summary>
        public static string Placeholder_OldPassword {
            get {
                return ResourceManager.GetString("Placeholder_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your password.
        /// </summary>
        public static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype the new password.
        /// </summary>
        public static string Placeholder_RepeatNewPassword {
            get {
                return ResourceManager.GetString("Placeholder_RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address or user name.
        /// </summary>
        public static string Placeholder_UserName {
            get {
                return ResourceManager.GetString("Placeholder_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products and documents you&apos;re allowed to work on.
        /// </summary>
        public static string Text_AuthorizedToWork {
            get {
                return ResourceManager.GetString("Text_AuthorizedToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last things done.
        /// </summary>
        public static string Text_LastDone {
            get {
                return ResourceManager.GetString("Text_LastDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Text_NA {
            get {
                return ResourceManager.GetString("Text_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next to do.
        /// </summary>
        public static string Text_NextToDo {
            get {
                return ResourceManager.GetString("Text_NextToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not enabled to work on any products.
        /// </summary>
        public static string Text_NoProductsToWork {
            get {
                return ResourceManager.GetString("Text_NoProductsToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Note.
        /// </summary>
        public static string Text_ReleaseNote {
            get {
                return ResourceManager.GetString("Text_ReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadmap.
        /// </summary>
        public static string Text_Roadmap {
            get {
                return ResourceManager.GetString("Text_Roadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Items.
        /// </summary>
        public static string Text_WorkItems {
            get {
                return ResourceManager.GetString("Text_WorkItems", resourceCulture);
            }
        }
    }
}
