//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youbiquitous.Renoir.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youbiquitous.Renoir.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given email address already exists in the system.
        /// </summary>
        public static string Err_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("Err_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string Err_Generic {
            get {
                return ResourceManager.GetString("Err_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate both email and password.
        /// </summary>
        public static string Err_IncompleteCredentials {
            get {
                return ResourceManager.GetString("Err_IncompleteCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string Err_InvalidCredentials {
            get {
                return ResourceManager.GetString("Err_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to finalize credentials validation.
        /// </summary>
        public static string Err_InvalidHttpContext {
            get {
                return ResourceManager.GetString("Err_InvalidHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string Err_InvalidInput {
            get {
                return ResourceManager.GetString("Err_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number exceeded.
        /// </summary>
        public static string Err_MaxExceeded {
            get {
                return ResourceManager.GetString("Err_MaxExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not complete the operation.
        /// </summary>
        public static string Err_OperationFailed {
            get {
                return ResourceManager.GetString("Err_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown just for test purposes.
        /// </summary>
        public static string Err_TestException {
            get {
                return ResourceManager.GetString("Err_TestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not authorized.
        /// </summary>
        public static string Err_UnauthorizedOperation {
            get {
                return ResourceManager.GetString("Err_UnauthorizedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weird, but no user seems to match provided identity.
        /// </summary>
        public static string Err_UserNotFound {
            get {
                return ResourceManager.GetString("Err_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string Label_Counter {
            get {
                return ResourceManager.GetString("Label_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string Label_DisplayName {
            get {
                return ResourceManager.GetString("Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the community.
        /// </summary>
        public static string Label_JoinCommunity {
            get {
                return ResourceManager.GetString("Label_JoinCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password (Repeat).
        /// </summary>
        public static string Label_NewPasswordRepeat {
            get {
                return ResourceManager.GetString("Label_NewPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Label_OldPassword {
            get {
                return ResourceManager.GetString("Label_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Page.
        /// </summary>
        public static string Label_SamplePage {
            get {
                return ResourceManager.GetString("Label_SamplePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since.
        /// </summary>
        public static string Label_Since {
            get {
                return ResourceManager.GetString("Label_Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay connected.
        /// </summary>
        public static string Label_StayConnected {
            get {
                return ResourceManager.GetString("Label_StayConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered users.
        /// </summary>
        public static string Label_Users {
            get {
                return ResourceManager.GetString("Label_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully done!.
        /// </summary>
        public static string Msg_Done {
            get {
                return ResourceManager.GetString("Msg_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public name.
        /// </summary>
        public static string Placeholder_DisplayName {
            get {
                return ResourceManager.GetString("Placeholder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password you want to use now.
        /// </summary>
        public static string Placeholder_NewPassword {
            get {
                return ResourceManager.GetString("Placeholder_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password currently in use.
        /// </summary>
        public static string Placeholder_OldPassword {
            get {
                return ResourceManager.GetString("Placeholder_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your password.
        /// </summary>
        public static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype the new password.
        /// </summary>
        public static string Placeholder_RepeatNewPassword {
            get {
                return ResourceManager.GetString("Placeholder_RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address or user name.
        /// </summary>
        public static string Placeholder_UserName {
            get {
                return ResourceManager.GetString("Placeholder_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Text_NA {
            get {
                return ResourceManager.GetString("Text_NA", resourceCulture);
            }
        }
    }
}
