///////////////////////////////////////////////////////////////////
//
// Project RENOIR
// Release Notes Instant Reporter
//
// Reference application presented in
// Clean Architecture with .NET (MS Press) 2024
// Author: Dino Esposito
// 
//

using System.ComponentModel.DataAnnotations;

namespace Youbiquitous.Renoir.DomainModel.WorkInProgress;

/// <summary>
/// Tracked work item (things done, to-do, bugs)
/// </summary>
public class WorkItem : BaseEntity
{
    public WorkItem()
    {
        Type = WorkItemType.Feature;
    }

    /// <summary>
    /// Unique ID (autogenerated)
    /// </summary>
    public long Id { get; set; }
    
    /// <summary>
    /// Brief title of the item
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// Longer item description
    /// </summary>
    [MaxLength(200)]
    public string Description { get; set; }

    /// <summary>
    /// Type of the item: Feature, etc
    /// </summary>
    public WorkItemType Type { get; set; }

    /// <summary>
    /// Status of the item: Done, Scheduled, Fixed, Pending
    /// </summary>
    public WorkItemStatus Status { get; set; }
}
