///////////////////////////////////////////////////////////////////
//
// Project RENOIR
// Release Notes Instant Reporter
//
// Reference application presented in
// Clean Architecture with .NET (MS Press) 2024
// Author: Dino Esposito
// 
//

using System.ComponentModel.DataAnnotations;

namespace Youbiquitous.Renoir.DomainModel;

/// <summary>
/// PRODUCT entity (properties)
/// </summary>
public partial class Product : BaseEntity
{
    /// <summary>
    /// Ctor, mostly needed for EF and to save us an entire layer of DTOs
    /// </summary>
    public Product()
    {
    }
    
    /// <summary>
    /// Unique ID (autogenerated)
    /// </summary>
    public long ProductId { get; set; }

    /// <summary>
    /// Product name
    /// </summary>
    [MaxLength(50)]
    public string Name { get; set; }


}
