//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youbiquitous.Renoir.DomainModel.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InternalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youbiquitous.Renoir.DomainModel.Utils.InternalStrings", typeof(InternalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        internal static string Text_Category_Bug {
            get {
                return ResourceManager.GetString("Text_Category_Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        internal static string Text_Category_Feature {
            get {
                return ResourceManager.GetString("Text_Category_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        internal static string Text_Category_Internal {
            get {
                return ResourceManager.GetString("Text_Category_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string Text_Category_None {
            get {
                return ResourceManager.GetString("Text_Category_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Note.
        /// </summary>
        internal static string Text_Document_ReleaseNote {
            get {
                return ResourceManager.GetString("Text_Document_ReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadmap.
        /// </summary>
        internal static string Text_Document_Roadmap {
            get {
                return ResourceManager.GetString("Text_Document_Roadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo List.
        /// </summary>
        internal static string Text_Document_TodoList {
            get {
                return ResourceManager.GetString("Text_Document_TodoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Text_Position_Bottom {
            get {
                return ResourceManager.GetString("Text_Position_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given position.
        /// </summary>
        internal static string Text_Position_Specific {
            get {
                return ResourceManager.GetString("Text_Position_Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Text_Position_Top {
            get {
                return ResourceManager.GetString("Text_Position_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Section.
        /// </summary>
        internal static string Text_ReleaseNote_NewSection {
            get {
                return ResourceManager.GetString("Text_ReleaseNote_NewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Text_User_Unknown {
            get {
                return ResourceManager.GetString("Text_User_Unknown", resourceCulture);
            }
        }
    }
}
